# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MeCsWWm2VZcIbGRyUStfSfH-8hyKbub5
"""

from google.colab import drive
drive.mount('/content/my_drive/')

cd my_drive

cd My\ Drive

cd keras

import keras
keras.__version__

!ls

!python3 train_frcnn_new.py -o simple -p annotation.txt

!pip uninstall tensorflow

!pip install keras==2.2.0

!pip install tensorflow-gpu==1.8.0

!wget https://developer.nvidia.com/compute/cuda/9.0/Prod/local_installers/cuda-repo-ubuntu1604-9-0-local_9.0.176-1_amd64-deb

!dpkg -i cuda-repo-ubuntu1604-9-0-local_9.0.176-1_amd64-deb

!apt-key add /var/cuda-repo-9-0-local/7fa2af80.pub

!apt-get update

!apt-get install cuda=9.0.176-1

!python3 train_frcnn_new.py -o simple -p annotate.txt